name: Release Charts

on:
  push:
    branches:
      - main
      - fix-helm-chart-release-chart-dir

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: docker-hub-rate-limit-exporter


      - name: Configure Git
        run: |
          cd ./docker-hub-rate-limit-exporter
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Check dir
        run: |
          pwd
          ls -all
          cd ./docker-hub-rate-limit-exporter
          pwd
          ls -all
          cd ..
          cd ..
          pwd
          ls -all
          cd ..
          pwd
          ls -all
          cd ..
          ls -all
          pwd

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
